### ISSUE TITLE
fix: 블로그 생성 완료시 메인페이지 이동관련 404

### ISSUE THREAD

**Issue by zeroGone** [zeroGone/studylog#13]
현재 블로그 이름을 url로 사용할 예정이였으나

블로그 이름이 한글일경우와 띄어쓰기가 포함될 경우 어떻게 처리할 것인가에 대해 논의해야함.

**Comment by JinminYANG** [comment]
1안. url 부분을 따로 입력하여 영문과 띄어쓰기 없이 작성하게 한다.
2안. url 부분을 따로 입력하여 영문을 입력하게 하고 띄어쓰기를 _ 처리한다.
3안. 블로그 이름을 영문과 띄어쓰기 없이 작성하게 한다.
3안. 블로그 이름을 영문으로 작성하고 띄어쓰기를 _ 처리한다.
5안. url(블로그이름)을 한글로 입력하였을 경우 인코딩처리한다.

일단 생각나는대로 작성해보았습니다.

**Comment by zeroGone** [comment]
띄어쓰기 같은 경우는 _ 처리하는게 맞다고 생각합니다. GitHub의 경우 실제로 레포지토리 이름에 띄어쓰기가 있을 경우 - 로 파싱해서 처리합니다.
한글로 입력했을 경우 인코딩하면 %쌸라쌸라로 되기 때문에 이상하게 보여질 것 같으니 영어만 허용하는게 어떨까요

**Comment by JinminYANG** [comment]
url을 따로 입력하지않고 블로그 이름 작성란을 이용하여 블로그를 생성하는 것은 동일하게 진행하는건가요?

**Comment by zeroGone** [comment]
띄어쓰기 같은 경우 블로그 생성 시에 -나 _로 바뀐다고 유저에게 알리는 문구가 필요하다고 생각하고 해당 메인페이지로 이동할때 parsing 작업이 필요하다고 생각합니다
그리고 편하게 영어만 할 수 있게 할까요?

**Comment by JinminYANG** [comment]
알리는 문구를 form안에 남겨두는 것은 어떨까요?

영어만 작성하게 하는 것이 편할 것 같습니다.

**Comment by zeroGone** [comment]
그거에 대해서는 알아서 해주시면 감사하겠습니다~~
