### ISSUE TITLE
feat: 블로그 생성시 수정사항

### ISSUE THREAD

**Issue by JinminYANG** [zeroGone/studylog#27]
1. 현재 영어와 숫자만 사용한 기능을 요청에따라 한글도 사용가능하게 수정하겠습니다.
2. 멤버 검색 부분에서 현재 사용자 계정 검색부분을 프론트에서 처리하도록 수정하겠습니다.
3-1. 멤버 검색 성공시 status 200을 반환받아 등록시킨다.
3-2. 멤버 검색 실패시 status 404를 반환받고 errorMessage도 반환받고 사용자에게 알려준다.

**Comment by zeroGone** [comment]
#46
